Fix "redefines-builtin-id" linting error:
```
redefines-builtin-id: redefinition of the built-in function new
```

This is basically shadowing a built in method, which is a bad practice.

Signed-off-by: Brendan Winter <bwinter@vmware.com>
Signed-off-by: mccoyale <alexandram@vmware.com>